# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # - name: Update Chrome to be compatible with ChromeDriver for e2e tests
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install chromium-driver google-chrome-stable
      - run: npm ci
      - run: npm run lint
      - run: npm run build-for-prod
      - run: npm run ci-test
      # TODO FB-1 Migrate to Cypress after upgrading to Angular 12
      # - run: npm run e2e
        env:
          CI: true
